### ISSUE TITLE
MissingMethodException: No signature of method: org.yaml.snakeyaml.Yaml.loadAs()

### ISSUE THREAD

**Issue by monksy** [robfletcher/betamax#153]
I'm developing a Grails 2.4.3 application. I'm using Betamax 1.1.2.

I'm trying to use Betamax to record the sessions and play them back for the tests. I have a class that uses a RestClient object to make the request. [It's in Client as _meetupBase]

Why I'm getting the issue that it can't locate a loadAs function, is just beyond me. The tape for the test was written, and this only happens when I try to play it back.

The test file is:

   class ClientTest extends Specification {
        @Rule Recorder recorder = new Recorder(
                tapeRoot: new File(BuildSettingsHolder.settings?.baseDir, 'test/resources/tapes'),
                ignoreLocalhost: true ,
                sslSupport: true
        )
   
    void setupSpec() {
        TapePropertyUtils.metaClass.sort = {Set<Property> properties, List<String> names ->
            new LinkedHashSet(properties.sort(true, new OrderedPropertyComparator(names)))
        }
    }

    @Betamax(tape = 'meetupEventsList')
    void testListEvents() {
        when:
        def instance =  new Client('....')
        def meetupBase = new RESTClient('http://api.meetup.com/2/')
        BetamaxRoutePlanner.configure(meetupBase.client)
        meetupBase.client.removeRequestInterceptorByClass( ContentEncoding.RequestInterceptor.class )
        meetupBase.client.removeResponseInterceptorByClass( ContentEncoding.ResponseInterceptor.class )
        instance._meetupBase = meetupBase

        def events = instance.listEvents('Chicago-Reddit-Meetup')

        then:
        log.info("List of events: {events}")

    }
   }

However, I'm getting the exception;

Exception:

   groovy.lang.MissingMethodException: No signature of method: org.yaml.snakeyaml.Yaml.loadAs() is      applicable for argument types: (java.io.BufferedReader, java.lang.Class) values: [java.io.BufferedReader@35d4035f, class co.freeside.betamax.tape.yaml.YamlTape]
    Possible solutions: load(java.io.InputStream), load(java.io.Reader), load(java.lang.String),   loadAll(java.io.InputStream), loadAll(java.io.Reader), loadAll(java.lang.String)
 	at co.freeside.betamax.tape.yaml.YamlTape.readFrom(YamlTape.groovy:41)
	at co.freeside.betamax.tape.yaml.YamlTapeLoader.loadTape_closure1(YamlTapeLoader.groovy:41)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at co.freeside.betamax.tape.yaml.YamlTapeLoader.loadTape(YamlTapeLoader.groovy:40)
	at co.freeside.betamax.Recorder.insertTape(Recorder.groovy:121)

**Comment by monksy** [comment]
The issue with this was due to Grails 2.4.4 bringing in snakesyml 1.8. 

To fix this:
Defined the SnakeYML dependency.
 build 'org.yaml:snakeyaml:1.10'

**Comment by arudge** [comment]
same issue, thanks for posting your resolution.
